# Generated by Django 2.2.7 on 2019-11-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0002_auto_20191106_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
